remove iniparser fix
Looks like it's causing an extremely weird error:

       error: symlinkJoin requires either a `name` OR `pname` and `version`

Nix at its best, not really telling me where this issue is (how about
just tell me WHERE EXACTLY the symlinkJoin comes from and WHERE EXACTLY
it is missing either a name or pname and version)

The stack trace just mentions remove-fetchcontent-usage.patch and after
looking in nixpkgs, that occurs in iniparser.